version: '3.8'

services:
  php-apache-backend:
    build: .
    container_name: php-apache-backend
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html
      - ./src:/var/www/html/src
      - ./php/apache-config.conf:/etc/apache2/conf-enabled/apache-config.conf
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: 1234
      DB_NAME: db_amita

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: db_amita
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: 1234
    depends_on:
      - mysql

volumes:
  mysql_data:


